### ISSUE TITLE
Not working on ContentBerg

### ISSUE THREAD

**Issue by olu4mide** [nielslange/smntcs-custom-logo-link#103]
I tried using the plugin on the ContentBerg theme, but it is not working.

**Comment by nielslange** [comment]
Hello @olu4mide 👋

Thanks for reaching out. I see that [Contentberg](https://themeforest.net/item/contentberg-blog-content-marketing-theme/22634637) is a premium theme from [themeforest.net](https://themeforest.net). As that theme is not Open-Source, I cannot test the implementation. As a result of that, I stopped supporting premium themes a while ago. That said, as it's a premium theme, I'm sure the theme developers can assist you on how to link the custom logo. You can contact their support directly via https://themeforest.net/item/contentberg-blog-content-marketing-theme/22634637/support.

I'll close this issue for now, but you are welcome to open another issue if you have further questions or suggestions regarding Open-Source themes.
