### ISSUE TITLE
Add support for Suffice theme

### ISSUE THREAD

**Issue by turuto** [nielslange/smntcs-custom-logo-link#27]
Hi, Could you please add support for the Suffice Theme?
https://demo.themegrill.com/suffice/

**Comment by nielslange** [comment]
Sure, @turuto! I'll enhance the plugin and will release an update soon. 😀

**Comment by turuto** [comment]
Thanks a lot!

**Comment by nielslange** [comment]
@turuto I just release a new version of the plugin with supports the Suffice theme. Thanks for suggesting this feature and if you like the plugin, it would be great if you could leave a review on https://wordpress.org/support/plugin/smntcs-custom-logo-link/reviews/ 😀
