### ISSUE TITLE
Please add support for wptouch 

### ISSUE THREAD

**Issue by harrismint** [nielslange/smntcs-custom-logo-link#36]
Hi - this plugin is working well on my main theme, but not with the WPtouch plugin for mobile. Any chance it could be added?

Thanks

**Comment by nielslange** [comment]
Hello @harrismint 👋 

Please excuse my delayed response. I looked into this case and found out that when having the WPtouch plugin active, the tests are no longer running. The WPtouch plugin  also seems to alter the default responsive behaviour of the themes. Therefore, I decided not to add support for the WPtouch plugin for now. That said, if you find a way to add support while ensuring that all test cases can still be executed, feel free to create a PR.
