### ISSUE TITLE
Add support for Rodberg theme

### ISSUE THREAD

**Issue by ghost** [nielslange/smntcs-custom-logo-link#48]

**Comment by nielslange** [comment]
See https://themeforest.net/item/rodberg-travel-blog-wordpress-theme-gutenberg-compatible/22641571

**Comment by nielslange** [comment]
Hello @adityaswarup241 👋 I contacted the theme developer regarding a developer license to add support for the Rodberg theme. To ensure that the implementation works as expected, I need to cover it by a test case. This requires that I have access to the theme. To ensure that the theme hasn't been tempered with and that it does not contain malicious code, I can only accept the original theme by the theme developer.
