### ISSUE TITLE
Add support for Gutentype theme

### ISSUE THREAD

**Issue by sorenfillet** [nielslange/smntcs-custom-logo-link#52]

**Comment by nielslange** [comment]
See https://themeforest.net/item/gutentype-gutenberg-wordpress-blog-theme/22486033

**Comment by nielslange** [comment]
Hello @sorenfillet 👋 I contacted the theme developer regarding a developer license to add support for the Gutentype theme. To ensure that the implementation works as expected, I need to cover it by a test case. This requires that I have access to the theme. To ensure that the theme hasn't been tempered with and that it does not contain malicious code, I can only accept the original theme by the theme developer.

**Comment by sorenfillet** [comment]
Hello Niels! Any update on this? Thanks!

**Comment by nielslange** [comment]
Hello @sorenfillet 👋

Please note that I will no longer add support for premium themes. I believe in Open Source, and I'm happy to add support for all themes that are available via https://wordpress.org/themes/. I suggest that you contact the developer of the Gutentype theme directly to add this functionality to their theme.
