### ISSUE TITLE
Add support for Organic Purpose Theme

### ISSUE THREAD

**Issue by ahmedkahhh** [nielslange/smntcs-custom-logo-link#66]
please Add support for Organic Purpose Theme it does not work

**Comment by nielslange** [comment]
Hello @ahmedkahhh 👋

Please note that I will no longer add support for premium themes. I believe in Open Source, and I'm happy to add support for all themes that are available via https://wordpress.org/themes/. I suggest that you contact the developer of the Organic Purpose theme directly to add this functionality to their theme.
