### ISSUE TITLE
please Add support for WPRentals 

### ISSUE THREAD

**Issue by cedricgattaz** [nielslange/smntcs-custom-logo-link#67]
please Add support for WPRentals Theme it does not work

**Comment by nielslange** [comment]
Hello @cedricgattaz 

Please note that I will no longer add support for premium themes. I believe in Open Source, and I'm happy to add support for all themes that are available via https://wordpress.org/themes/. I suggest that you contact the developer of the WPRentals theme directly to add this functionality to their theme.
