### ISSUE TITLE
Add support for the Customify theme

### ISSUE THREAD

**Issue by sebveigli** [nielslange/smntcs-custom-logo-link#75]
Hey there,

Thanks for everything you do for the community. Is there any chance you would be able to extend for support for the Customify theme?

Thanks in advance!

**Comment by nielslange** [comment]
See https://wordpress.org/themes/customify/

**Comment by nielslange** [comment]
Hello @sebveigli 👋

Thanks for reaching out, and apologies for my delayed response. I looked into this and noticed that the plugin already supports the [Customify](https://wordpress.org/themes/customify/) theme. Is it not working on your end?

**Comment by koenpolder** [comment]
Hi Niels,

Thank you for creating the plugin. Unfortunately the Plugin doesn't seem to work in the Customify theme. It installs just fine and the 'logo link' button appears in the customizer menu. After changing the URL there, nothing changes though. It still links to 'home'. Do you maybe have a solution?

Kind Regards,

Koen

**Comment by nielslange** [comment]
> Thank you for creating the plugin. Unfortunately the Plugin doesn't seem to work in the Customify theme. It installs just fine and the 'logo link' button appears in the customizer menu. After changing the URL there, nothing changes though. It still links to 'home'. Do you maybe have a solution?

Hi @koenpolder 👋

Thanks for reaching out! I noticed that while the textual link of the Customify theme is working as expected, linking the logo wasn't working. I just went ahead and fixed this. If you update the plugin, it should work as expected. Please let me know, in case it does not work as expected. 😉

It also seems that you took the effort to creating a GitHub account to report this issue. This is wonderful. Thanks for people like you, software like my plugin can become better. Keep up reporting issues when you notice them! 🙌
