### ISSUE TITLE
Additional Theme

### ISSUE THREAD

**Issue by gbyerly** [nielslange/smntcs-custom-logo-link#82]
Please add the Total theme by WPExplorer to this plugin.

**Comment by nielslange** [comment]
Hell @gbyerly 👋

Thanks for reaching out! As the Total theme by WPExplorer is a premium theme, to which I don't have access, I cannot make this plugin compatible with it. That said, given that it's a premium theme, I suggest reaching out to the theme developers to suggesting this feature.
