### ISSUE TITLE
Now working on Divi

### ISSUE THREAD

**Issue by simonezanetti71** [nielslange/smntcs-custom-logo-link#96]
**Describe the bug**
The website I'm using the plugin in is https://it.still33.com
I'm trying to have the logo to point to https://still33.com instead of https://it.still33.com
I configured the URL in the settingsplugin setting but it's not working.
Clikcing the link it still takes you to https://it.still33.com and not to https://still33.com 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nielslange** [comment]
Hello @simonezanetti71 👋

Thanks for reaching out. As the [Divi theme](https://www.elegantthemes.com/gallery/divi/), from Elegantthemes, is not Open-Source, I cannot test the implementation. As a result of that, I stopped supporting premium themes a while ago. That said, as it's a premium theme, I'm sure the theme developers can assist you on how to link the custom logo. You can contact their support directly via https://www.elegantthemes.com/members-area/login/.

I'll close this issue for now, but you are welcome to open another issue if you have further questions or suggestions regarding Open-Source themes.
